---
apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: streamify
type: Opaque
data:
  STEAM_API_SECRET: YOUR_BASE64_ENCODED_STEAM_API_SECRET
  JWT_SECRET_KEY: YOUR_BASE64_ENCODED_JWT_SECRET_KEY