---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-pv
  namespace: streamify
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/mongodb"
