---
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: streamify
type: Opaque
data:
  # base64 encoded values
  mongo-root-username: bW9uZ29hZG1pbg==   # "mongoadmin"
  mongo-root-password: c2VjdXJlcGFzcw==   # "securepass"
