---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: streamify
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: anonymous292009/chat-client:latest
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: frontend-config
          resources:
            requests:
              cpu: "20m"
              memory: "16Mi"
            limits:
              cpu: "100m"
              memory: "64Mi"

